<?php get_header(); $base=get_template_directory_uri(); ?>
<main>
<section class="hero" id="home">
  <div class="wrap hero-reference">
    <img class="hero-reference-image" src="<?php echo esc_url($base.'/assets/img/hero-reference-user-v19.jpg'); ?>" alt="PR агентство в Москве — PRодвижение">
    <div class="hero-click-zones" aria-label="Быстрые переходы">
      <a class="hero-click hero-click-project" href="#contact" aria-label="Обсудить проект"></a>
      <a class="hero-click hero-click-services" href="#directions" aria-label="Перейти к услугам"></a>
    </div>
    <div class="hero-pills-overlay" aria-label="Основные направления"><div><span>▥</span> МЕДИА</div><div><span>♢</span> РЕПУТАЦИЯ</div><div><span>🚀</span> ПРОДВИЖЕНИЕ</div><div><span>◇</span> БРЕНДИНГ</div><div><span>♙</span> СОБЫТИЯ</div><div><span>♧</span> ЛЮДИ</div></div>
    <div class="hero-semantic" aria-hidden="false">
      <h1>PR агентство в Москве</h1>
      <p>Продюсерский центр нового поколения. Продвигаем людей, бренды и идеи в медиа, социальных сетях и реальной жизни.</p>
    </div>
  </div>
</section>

<section class="section services-section" id="directions"><div class="wrap"><div class="section-head"><div><span class="kicker">PR · ПРОДВИЖЕНИЕ · ПРОДЮСИРОВАНИЕ</span><h2>Наши услуги</h2><p class="lead">Основные направления PRодвижения — от артистов и музыки до бизнеса, политики, сайтов, SEO и социальных сетей.</p></div><a href="<?php echo esc_url(home_url('/?page_id=324')); ?>">Все PR-услуги →</a></div><div class="services"><?php $services=[['ref-service-1.jpg','Продвижение артистов','Релизы, ротации, СМИ, концерты, PR.','/?page_id=844'],['ref-service-2.jpg','PR для бизнеса','Репутация, СМИ, антикризис, позиционирование.','/?page_id=324'],['ref-service-3.jpg','Продюсерский центр','Концертный директор, PR-менеджер, проекты.','/?page_id=88'],['ref-service-4.jpg','SMM и соцсети','VK, Telegram, Одноклассники, контент и реклама.','/?cat=321'],['ref-service-5.jpg','Сайты и SEO','Создание, оптимизация, продвижение и Яндекс.','/?p=894'],['ref-service-6.jpg','События и концерты','Концерты, туры, мероприятия, презентации.','/?page_id=844']]; foreach($services as $s): ?><article class="service"><a href="<?php echo esc_url(home_url($s[3])); ?>"><img src="<?php echo esc_url($base.'/assets/img/'.$s[0]); ?>" alt="<?php echo esc_attr($s[1]); ?>"><div class="service-body"><h3><?php echo esc_html($s[1]); ?></h3><p><?php echo esc_html($s[2]); ?></p><span class="arrow">→</span></div></a></article><?php endforeach; ?></div></div></section>

<section class="section seo-directions" id="directions-seo"><div class="wrap"><div class="section-head"><div><span class="kicker">НАПРАВЛЕНИЯ · PR · SEO · DIGITAL</span><h2>Продвигаем проекты в разных нишах</h2><p class="lead">Системно работаем с репутацией, медиа, брендами, артистами, политическими проектами, сайтами и digital-коммуникациями.</p></div></div><div class="direction-grid">
<a class="direction d1" href="<?php echo esc_url(home_url('/?page_id=844')); ?>"><div class="direction-copy"><span class="direction-num">01</span><b>Артисты<br>и музыка</b></div><img src="<?php echo esc_url($base.'/assets/img/ref-direction-1.jpg'); ?>" alt="Продвижение артистов и музыкальный PR"></a>
<a class="direction d2" href="<?php echo esc_url(home_url('/?page_id=1804')); ?>"><div class="direction-copy"><span class="direction-num">02</span><b>Политический<br>PR</b></div><img src="<?php echo esc_url($base.'/assets/img/ref-direction-2.jpg'); ?>" alt="Политический PR и коммуникации"></a>
<a class="direction d3" href="<?php echo esc_url(home_url('/?page_id=324')); ?>"><div class="direction-copy"><span class="direction-num">03</span><b>PR бизнеса<br>и брендов</b></div><img src="<?php echo esc_url($base.'/assets/img/ref-direction-3.jpg'); ?>" alt="PR бизнеса и брендов"></a>
<a class="direction d4" href="<?php echo esc_url(home_url('/?p=894')); ?>"><div class="direction-copy"><span class="direction-num">04</span><b>Сайты<br>и SEO</b></div><img src="<?php echo esc_url($base.'/assets/img/ref-direction-4.jpg'); ?>" alt="Создание сайтов и SEO-продвижение"></a>
<a class="direction d5" href="<?php echo esc_url(home_url('/?cat=321')); ?>"><div class="direction-copy"><span class="direction-num">05</span><b>VK<br>и соцсети</b></div><img src="<?php echo esc_url($base.'/assets/img/ref-direction-5.jpg'); ?>" alt="Продвижение VK и социальных сетей"></a>
<a class="direction d6" href="<?php echo esc_url(home_url('/?cat=373')); ?>"><div class="direction-copy"><span class="direction-num">06</span><b>Telegram<br>и мессенджеры</b></div><img src="<?php echo esc_url($base.'/assets/img/ref-direction-6.jpg'); ?>" alt="Продвижение Telegram и мессенджеров"></a>
<a class="direction d7" href="<?php echo esc_url(home_url('/?page_id=1733')); ?>"><div class="direction-copy"><span class="direction-num">07</span><b>Репутация<br>и антикризис</b></div><img src="<?php echo esc_url($base.'/assets/img/ref-direction-7.jpg'); ?>" alt="Управление репутацией и антикризисный PR"></a>
<a class="direction d8" href="<?php echo esc_url(home_url('/?page_id=290')); ?>"><div class="direction-copy"><span class="direction-num">08</span><b>Писатели, поэты,<br>художники</b></div><img src="<?php echo esc_url($base.'/assets/img/ref-direction-8.jpg'); ?>" alt="Продвижение писателей, поэтов и художников"></a>
</div></div></section>

<section class="section metrics-section"><div class="wrap"><div class="rainbow"><div class="metric m1"><b>♫</b><strong>+3 000 000</strong><span>прослушиваний треков</span></div><div class="metric m2"><b>▤</b><strong>100+</strong><span>публикаций в СМИ</span></div><div class="metric m3"><b>▥</b><strong>x5</strong><span>рост узнаваемости брендов</span></div><div class="metric m4"><b>♧</b><strong>500+</strong><span>проектов и клиентов</span></div></div></div></section>

<section class="section story-section" id="about"><div class="wrap story-grid"><div class="story"><div class="story-content"><span class="story-kicker">PR · МЕДИА · РЕПУТАЦИЯ</span><h2>Создаем истории,<br>которые звучат</h2><p>Помогаем талантам, экспертам, компаниям и проектам быть заметными, востребованными и успешными.</p><a class="story-link" href="#contact">Обсудить задачу →</a></div></div><div><div class="section-head mini"><div><span class="kicker">ПОЧЕМУ МЫ</span><h2>Почему выбирают нас</h2></div><a href="#contact">Все преимущества →</a></div><div class="why"><div class="why-card why-1"><b>♧</b><h3>Комплексный подход</h3><p>Стратегия 360°</p></div><div class="why-card why-2"><b>⚙</b><h3>Прозрачная работа</h3><p>Понятные KPI</p></div><div class="why-card why-3"><b>◇</b><h3>Сильные связи</h3><p>В медиа и индустрии</p></div><div class="why-card why-4"><b>♜</b><h3>Реальные результаты</h3><p>Долгосрочный эффект</p></div></div></div></div></section>

<section class="section cases-section" id="cases"><div class="wrap">
<div class="section-head mini"><div><span class="kicker">ПРИМЕРЫ РАБОТ · PR · MEDIA · DIGITAL</span><h2>Наши кейсы</h2><p class="lead">Практические направления работы: от продвижения артистов и бизнеса до сайтов, SEO и событий.</p></div><a href="#contact">Обсудить ваш проект →</a></div>
<div class="cases cases-v19">
<a class="case case-v19 c1" href="#contact"><div class="case-top"><span class="case-num">01</span><span class="case-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 18V6l10-3v12"/><circle cx="6" cy="18" r="3"/><circle cx="16" cy="15" r="3"/></svg></span></div><h3>Продвижение артистов</h3><p>PR артиста, релизы, публикации в СМИ, медиа-поддержка и развитие аудитории.</p><div class="case-bottom"><b>PR · MEDIA · MUSIC</b><span>→</span></div></a>
<a class="case case-v19 c2" href="#contact"><div class="case-top"><span class="case-num">02</span><span class="case-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20V10l8-6 8 6v10"/><path d="M8 20v-6h8v6"/></svg></span></div><h3>PR бизнеса и брендов</h3><p>Позиционирование, СМИ, репутация, экспертность и антикризисные коммуникации.</p><div class="case-bottom"><b>PR · BRAND · REPUTATION</b><span>→</span></div></a>
<a class="case case-v19 c3" href="#contact"><div class="case-top"><span class="case-num">03</span><span class="case-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 19h16"/><path d="M6 16V8l6-4 6 4v8"/><path d="M9 12h6"/></svg></span></div><h3>Сайты и SEO</h3><p>Создание и развитие сайта, SEO-структура, контент и продвижение в поиске.</p><div class="case-bottom"><b>WEB · SEO · DIGITAL</b><span>→</span></div></a>
<a class="case case-v19 c4" href="#contact"><div class="case-top"><span class="case-num">04</span><span class="case-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 20V8h14v12"/><path d="M3 8h18"/><path d="M8 4h8v4H8z"/><path d="M9 12h6M9 16h6"/></svg></span></div><h3>События и концерты</h3><p>Организация мероприятий, концертный PR, презентации и информационное сопровождение.</p><div class="case-bottom"><b>EVENT · PR · MEDIA</b><span>→</span></div></a>
</div></div></section>

<section class="section materials-section" id="materials"><div class="wrap"><div class="section-head"><div><span class="kicker">ЭКСПЕРТНЫЙ БЛОГ · PR · МЕДИА · DIGITAL</span><h2>Последние новости и статьи</h2><p class="lead">На главной показываем только свежие материалы. Все новые публикации добавляются через стандартный раздел WordPress «Записи» и автоматически появляются здесь.</p></div><a href="<?php echo esc_url(home_url('/stati/')); ?>">Все материалы →</a></div><div class="blog-grid"><?php $q=new WP_Query(['posts_per_page'=>15,'post_status'=>'publish','ignore_sticky_posts'=>true]); $icons=['PR','SEO','SMM','MEDIA','BRAND','ART','WEB','PR','DIGITAL','MEDIA','SEO','PR','MUSIC','REPUTATION','CONTENT']; $n=0; if($q->have_posts()): while($q->have_posts()): $q->the_post(); $icon=$icons[$n] ?? 'PR'; ?><article class="post"><a href="<?php the_permalink(); ?>"><?php if(has_post_thumbnail()): ?><div class="post-media"><?php the_post_thumbnail('medium_large',['class'=>'post-img']); ?><span class="post-icon"><?php echo esc_html($icon); ?></span></div><?php else: ?><div class="post-media post-placeholder"><span class="post-placeholder-word"><?php echo esc_html($icon); ?></span><span class="post-icon"><?php echo esc_html($icon); ?></span></div><?php endif; ?><div class="post-body"><span class="post-date"><?php echo esc_html(get_the_date('d.m.Y')); ?></span><h3><?php the_title(); ?></h3><p><?php echo esc_html(wp_trim_words(get_the_excerpt(),22)); ?></p><span class="post-more">Читать материал <b>→</b></span></div></a></article><?php $n++; endwhile; wp_reset_postdata(); else: ?><article class="post"><div class="post-body"><h3>PR-агентство Москва</h3><p>Новости и экспертные материалы о PR, продвижении, репутации и брендинге.</p></div></article><?php endif; ?></div></div></section>

<section class="section contact-section" id="contact"><div class="wrap"><div class="cta-band"><div><span class="kicker">ГОТОВЫ НАЧАТЬ?</span><h2>Готовы обсудить ваш проект?</h2><p>Получите индивидуальную консультацию и стратегию продвижения под ваши цели.</p></div><a class="cta" href="tel:+79778240200">Позвонить +7 (977) 824-02-00 →</a><em>Ваш успех<br>начинается здесь!</em></div></div></section>
</main><?php get_footer(); ?>
